[package]
name = "math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
quick-error = "2.0.1"
serde = "1.0.183"
shellfish = "0.8.0"
rustyline = "11.0.0"
