[package]
name = "hydralang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
rustyline = "11.0.0"
pest = "2.7.3"
pest_derive = "2.7.3"
