WHITESPACE = _{ " " }
COMMENT = _{ "#" ~ (!("#"|NEWLINE) ~ ANY)* ~ ("#"|NEWLINE) } 

number        = @{ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT*){0, 1} }
operator      =  { "+" | "-" | "*" | "/" | "^" | "$" | "%" }
var           = @{ !("where") ~ ASCII_ALPHA+ }
vector        =  { "(" ~ expr ~ ("," ~ expr)* ~ ")" }
function_call =  { function_name ~ "(" ~ expr ~ ("," ~ expr)* ~ ")" }


token = _{ number | operator | function_call | var | vector }

constraint      =  { "where" ~ "{" ~ (expr ~ ("," ~ expr)*)~ "}" }

function_name = @{ "_"{0, 1} ~ ASCII_ALPHA+ }
function_def  =  { function_head ~ statement ~ constraint{0, 1} ~ NEWLINE* }
function_head =  { function_name ~ "(" ~ " "* ~ expr ~ (" "* ~ "," ~ " "* ~ expr ~ " "*)* ~ ")" ~ " "* ~ "=" }

expr      = { token+ }
statement = { expr ~ NEWLINE* }
script    = { (function_def | statement | NEWLINE)+ }